language: csharp
mono: none
dotnet: 2.1.402
dist: trusty
sudo: required

install:
- dotnet restore

script:
 - dotnet build -c Release
 - dotnet pack -c Release

deploy:
  provider: script
  skip_cleanup: true
  script:
  - cd Wit.Ai.NET/bin/Release && dotnet nuget push *.nupkg --source $NUGET_FEEDURL --api-key $NUGET_APIKEY
  on:
    branch: master